default: &default
  adapter: mysql2
  pool: 20
  username: root
  # password: abc12345
  # host: cook-book-development.cusvaztgta1i.ap-south-1.rds.amazonaws.com

development:
  <<: *default
  database: cook_book_development

test:
  <<: *default
  database: cook_book_test
