default: &default
  adapter: postgresql
  pool: 20
  host: jelani.db.elephantsql.com

development:
  <<: *default
  username: itosakkx
  password: KrbM7rPX0NimKOLLCcf5SsqdxmGu4lHB
  database: itosakkx

test:
  <<: *default
  username: xuyuflpz
  password: ghkVdFMDRGb1oi-2Dm4kIdKwVwq_L_-G
  database: xuyuflpz
